// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 22specialcharacterfillinformnegativeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 22specialcharacterfillinformnegative() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1096, 672));
    js.executeScript("window.scrollTo(0,688)");
    js.executeScript("window.scrollTo(0,1870.6666259765625)");
    js.executeScript("window.scrollTo(0,4706)");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("~!@#$%^&*()_+{}|:”>?<Ё!”№;%:?*()_+/Ъ,/.,;’[]\\|");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mail@ya.ru");
    driver.findElement(By.id("input_1676828667932")).click();
    driver.findElement(By.id("input_1676828667932")).sendKeys("(911) 367-93-52");
    driver.findElement(By.cssSelector(".tn-form__submit:nth-child(8) > .t-submit")).click();
  }
}
